on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  run_ci_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: "Check commit message conventions"
        run: ./devel/scripts/check_commit_message.sh ${{ github.event.pull_request.head.sha }}

      - name: cargo test
        run: cargo test --all-features

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
