on: 
  push:
    branches: [main]

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: typst-community/setup-typst@v4
    - name: Build report
      run: typst compile --font-path fonts report.typ report.pdf
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "report.pdf"
        makeLatest: true
        name: "Report"
        tag: "latest"
